// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    DashbardButton: typeof import('./src/components/DashbardButton.vue')['default']
    DynamicFormItem: typeof import('./src/components/layout/DynamicFormItem.vue')['default']
    EchartsCard: typeof import('./src/components/EchartsCard.vue')['default']
    EntityDetail: typeof import('./src/components/layout/EntityDetail.vue')['default']
    EntityForm: typeof import('./src/components/layout/EntityForm.vue')['default']
    EntityTable: typeof import('./src/components/layout/EntityTable.vue')['default']
    GenericRemoteSelect: typeof import('./src/components/GenericRemoteSelect.vue')['default']
    NestDetail: typeof import('./src/components/layout/NestDetail.vue')['default']
    PermissionMenu: typeof import('./src/components/PermissionMenu.vue')['default']
    SearchSelect: typeof import('./src/components/SearchSelect.vue')['default']
  }
}

export { }
